name 'lfisher47-firewall_wrapper'
version '0.0.2'
source  'git://github.com/lfisher47/puppet-firewall_wrapper.git'
author  'Leah Fisher'
license 'Apache 2.0'
summary 'Wrapper around thias/rhel module.'
description 'Wrapper around thias/rhel module.'
dependency 'thias/rhel', '>= 0.2.3'
